# Generated by Django 5.1.5 on 2025-02-22 19:16

import FilmApp.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Возрастной рейтинг')),
            ],
            options={
                'verbose_name': 'Возрастной рейтинг',
                'verbose_name_plural': 'Возрастные рейтинги',
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тип контента',
                'verbose_name_plural': 'Типы контента',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, default=0.0, help_text='Средняя оценка от 0 до 10', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Средняя оценка')),
                ('votes', models.PositiveIntegerField(default=0, help_text='Общее количество голосов', verbose_name='Количество голосов')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание')),
                ('status', models.CharField(default='Нет статуса', max_length=255, verbose_name='Статус')),
                ('image_url', models.URLField(blank=True, default='', help_text='URL изображения постера', max_length=500, verbose_name='Изображение')),
                ('year', models.CharField(default='', help_text="Укажите год или диапазон (например, '2008' или '2008 – 2013')", max_length=255, validators=[FilmApp.models.validate_year], verbose_name='Год выхода')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('age_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_age_ratings', to='FilmApp.agerating', verbose_name='Возрастной рейтинг')),
                ('countries', models.ManyToManyField(blank=True, related_name='%(class)s_countries', to='FilmApp.country', verbose_name='Страны')),
                ('genres', models.ManyToManyField(blank=True, related_name='%(class)s_genres', to='FilmApp.genre', verbose_name='Жанры')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ratings', to='FilmApp.rating', verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание')),
                ('status', models.CharField(default='Нет статуса', max_length=255, verbose_name='Статус')),
                ('image_url', models.URLField(blank=True, default='', help_text='URL изображения постера', max_length=500, verbose_name='Изображение')),
                ('year', models.CharField(default='', help_text="Укажите год или диапазон (например, '2008' или '2008 – 2013')", max_length=255, validators=[FilmApp.models.validate_year], verbose_name='Год выхода')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('age_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_age_ratings', to='FilmApp.agerating', verbose_name='Возрастной рейтинг')),
                ('countries', models.ManyToManyField(blank=True, related_name='%(class)s_countries', to='FilmApp.country', verbose_name='Страны')),
                ('genres', models.ManyToManyField(blank=True, related_name='%(class)s_genres', to='FilmApp.genre', verbose_name='Жанры')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ratings', to='FilmApp.rating', verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='Аноним', max_length=100, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='FilmApp.film', verbose_name='Фильм')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='FilmApp.serial', verbose_name='Сериал')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(help_text='Оценка от 0 до 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='FilmApp.film', verbose_name='Фильм')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='FilmApp.serial', verbose_name='Сериал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка пользователя',
                'verbose_name_plural': 'Оценки пользователей',
            },
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['slug'], name='FilmApp_fil_slug_659384_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['created_at'], name='FilmApp_fil_created_385c28_idx'),
        ),
        migrations.AddIndex(
            model_name='serial',
            index=models.Index(fields=['slug'], name='FilmApp_ser_slug_a456f1_idx'),
        ),
        migrations.AddIndex(
            model_name='serial',
            index=models.Index(fields=['created_at'], name='FilmApp_ser_created_862f06_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['film'], name='FilmApp_rev_film_id_358891_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['serial'], name='FilmApp_rev_serial__999947_idx'),
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['user'], name='FilmApp_use_user_id_aee26c_idx'),
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['film'], name='FilmApp_use_film_id_1aba50_idx'),
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['serial'], name='FilmApp_use_serial__7480a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('user', 'film'), ('user', 'serial')},
        ),
    ]
