# Generated by Django 5.1.5 on 2025-01-26 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание фильма')),
                ('status', models.CharField(default='Нету статуса', max_length=255, verbose_name='Статус фильма')),
                ('image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Вставьте изображение')),
                ('rating', models.IntegerField(default='0', verbose_name='Оценка')),
                ('com', models.IntegerField(default='0', verbose_name='Отзывы')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Список фильма',
                'verbose_name_plural': 'Список фильмов',
            },
        ),
    ]
