# Generated by Django 5.1.5 on 2025-01-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Жанр фильма'),
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Название фильма'),
        ),
    ]
