# Generated by Django 5.1.5 on 2025-02-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmApp', '0002_film_genre_film_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='age',
            field=models.CharField(default='', max_length=255, verbose_name='Возрастной рейтинг фильма'),
        ),
        migrations.AddField(
            model_name='film',
            name='content_type',
            field=models.CharField(default='', max_length=255, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(default='', max_length=255, verbose_name='Жанр фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.CharField(default='', max_length=255, verbose_name='Год выхода фильма'),
        ),
    ]
