# Generated by Django 5.1.5 on 2025-03-26 23:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmApp', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films', to='FilmApp.contenttype', verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.PositiveIntegerField(help_text='Укажите год выхода фильма', validators=[django.core.validators.MinValueValidator(1888)], verbose_name='Год выхода'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='year',
            field=models.PositiveIntegerField(help_text='Укажите год выхода фильма', validators=[django.core.validators.MinValueValidator(1888)], verbose_name='Год выхода'),
        ),
    ]
