# Generated by Django 5.1.5 on 2025-02-12 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmApp', '0003_film_age_film_content_type_alter_film_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameS', models.CharField(max_length=255, verbose_name='Название сериалов')),
                ('descriptionS', models.TextField(default='Описание отсутствует', verbose_name='Описание сериала')),
                ('statusS', models.CharField(default='Нету статуса', max_length=255, verbose_name='Статус Сериала')),
                ('image_urlS', models.URLField(blank=True, default='', max_length=500, verbose_name='Вставьте изображение')),
                ('ratingS', models.IntegerField(default='0', verbose_name='Оценка')),
                ('genreS', models.CharField(default='', max_length=255, verbose_name='Жанр сериала')),
                ('yearS', models.CharField(default='', max_length=255, verbose_name='Год выхода сериала')),
                ('comS', models.IntegerField(default='0', verbose_name='Отзывы')),
                ('slugS', models.SlugField(blank=True, editable=False, unique=True)),
                ('created_atS', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания')),
                ('ageS', models.CharField(default='', max_length=255, verbose_name='Возрастной рейтинг сериала')),
                ('content_typeS', models.CharField(default='', max_length=255, verbose_name='Тип контента')),
            ],
            options={
                'verbose_name': 'Список Сериала',
                'verbose_name_plural': 'Список Сериалов',
            },
        ),
    ]
