# Generated by Django 5.1.5 on 2025-03-27 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmApp', '0003_film_content_type_alter_film_year_alter_serial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='FilmApp.contenttype', verbose_name='Тип контента'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
