# Generated by Django 5.1.5 on 2025-02-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmApp', '0004_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serial',
            old_name='ageS',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='comS',
            new_name='com',
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='content_typeS',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='created_atS',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='descriptionS',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='genreS',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='image_urlS',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='nameS',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='ratingS',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='statusS',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='yearS',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='slugS',
        ),
        migrations.AddField(
            model_name='serial',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
    ]
