# Generated by Django 5.1.5 on 2025-05-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilmApp', '0005_comment_quiz_quizquestion_userprofile_userquizresult_and_more'),
    ]

    operations = [
    ]
