# Generated by Django 5.1.5 on 2025-06-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilmApp', '0006_auto_20250528_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='userquizresult',
            name='quiz',
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='following_user',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_genres',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userquizresult',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='UserFollowing',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserQuizResult',
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
